# Configuration for dlt

[runtime]
log_level = "WARNING"  # System log level of dlt
dlthub_telemetry = true  # Enable/disable anonymous usage data reporting

[sources.popola_dlt]
base_url = "https://eisaelect.co.za/fr/m/eisachad2024"  # The base URL of your API
username = "mahadi2"  # API authentication username
password = "Mahadi2024"  # API authentication password

[destination.postgres.credentials]
drivername = "postgresql"
database = "eisa"
username = "root"
password = "root"
host = "localhost"
port = 5432
